# Generated by Django 2.2.4 on 2019-08-29 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagen',
            new_name='Image',
        ),
    ]
